# Generated by Django 3.2 on 2021-04-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0003_family_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family_Comment',
            new_name='Fcomment',
        ),
    ]
