# Generated by Django 3.2 on 2021-04-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapp', '0004_rename_family_comment_fcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blog_media')),
                ('alter', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
